import type { Metadata } from "next";
import "./admin/admin.css";
import { validateAgentParam } from "@/lib/server/server-actions";


export const metadata: Metadata = {
  title: "Admin - Superexpert AI",
  description: "Generated by create next app",
};

export default async function AgentLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div>
        <main className="p-4 mx-auto max-w-[800px]">
          {children}
        </main>
    </div>
  );
}
