import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./admin/admin.css";
import { notFound } from "next/navigation";
import { checkAgentName } from "@/lib/server/server-actions";
import { AgentContext } from '@/app/context/agent-context';


export const metadata: Metadata = {
  title: "Admin - Superexpert AI",
  description: "Generated by create next app",
};

export default async function AgentLayout({
  params,
  children,
}: Readonly<{
  params: { [key: string]: string };
  children: React.ReactNode;
}>) {
  // Check for valid agent name
  const { agent } = await params;
  const agentName = agent.toLowerCase();
  const isValidAgentName = await checkAgentName(agentName);
  console.log("agent", agent);
  console.log("isValidAgentName", isValidAgentName);
  if (!isValidAgentName) {
    notFound();
  }

  return (
    <AgentContext.Provider value={agentName}>
    <div>
        <main className="p-4 mx-auto max-w-[800px]">
          {children}
        </main>
    </div>
    </AgentContext.Provider>
  );
}
