import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./admin.css";


export const metadata: Metadata = {
  title: "Admin - Superexpert AI",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <main className="p-4 mx-auto max-w-[800px]">
          {children}
        </main>
    </div>
  );
}
